### ISSUE TITLE
Browser support (hypercore requires Node fs module)

### ISSUE THREAD

**Issue by jclem** [mafintosh/hypercore#131]
How is the browser support intended to work? I can't compile this with webpack or some other such build system because the main module requires `random-access-file`, which in turn requires `fs`. Is there some expected way of building hypercore for the browser that I'm missing?

**Comment by yoshuawuyts** [comment]
The best option would probably be https://github.com/substack/random-access-idb

**Comment by jclem** [comment]
Oh yeah I planned on using that—the issue, though, is that I can't even `require('hypercore')` because it automatically requires `random-access-file` which in turn requires `fs`.

**Comment by yoshuawuyts** [comment]
Yep, use `browserify` to package it up :sparkles:

**Comment by jclem** [comment]
Ah okay, I’ll give that a whirl. Thank you. I’ll try and open a PR with some simple instructions once I get it working, if that'd be a welcome contribution.
