### ISSUE TITLE
Issue with multiple writers

### ISSUE THREAD

**Issue by 0fork** [mafintosh/hypercore#134]
I'm trying to have multiple hypercore instances that write into same log and replicate via hyperdiscovery swarm. Currently I can get 1 separate writer and 1 separate listener working with pretty much boilerplate hyperdiscovery code but if I add another writer, updates from that are not replicated.

Both writers are using same set of keys (which I have verified now more times than I can count...) so am I missing something obvious here?

Only custom settings are `live: true` for swarm and `sparse: true` for hypercore. I'm using `ram()` as test storage.

**Comment by pfrazee** [comment]
@0fork By design, only one device/process should write to a hypercore. Hypercores are linear logs. If multiple processes or devices write to a hypercore without coordination, they'll create splits in the log (ie two messages at the same seq number).

**Comment by 0fork** [comment]
@pfrazee Thanks for answering. I was under the assumption that the design was able to handle multiple writers as long as the secret key matches. I'm rather bummed out to hear about this because it limits a lot what one could do with hypercore and I really like the simplicity of it.

In case somebody else runs into this constrain as well, [hyperdb](https://github.com/mafintosh/hyperdb) looks better fit for this.

**Comment by mafintosh** [comment]
@0fork exactly the point of hyperdb :) there is also room for another module that combines multiple hypercores into a "single one" with causal ordered events. Something like that is prob what you are looking for.
