### ISSUE TITLE
Multiple hypercores in a single hyperdiscovery swarm

### ISSUE THREAD

**Issue by altieres** [mafintosh/hypercore#140]
I'm trying to create a simple chat app. Each peer will have one hypercore feed, and will need to add / clone feeds he wants to talk to. Is it ok?!
The first problem I have is that I need to start swarm for each hypercore, is there a way to start the swarm with more than one hypercore? I'm thinking that I will have to create something like hyperdb, who has multiple writers...

**Comment by mafintosh** [comment]
You can easily swarm multiple hypercores by passing the previous replication stream to the next replicate call

``` js
var stream = core1.replicate({live: true})
core2.replicate({stream: stream}) // both cores replicate over this stream now
```

Let me know if you need any help setting that up
