### ISSUE TITLE
Expose access to root hashes

### ISSUE THREAD

**Issue by xloem** [mafintosh/hypercore#142]
To provide for https://github.com/mafintosh/hyperdb/issues/41 , it seems an API function must be added to retrieve the root hashes that concisely hash the content of the node.

These hashes are more useful than just the signature already provided, because signatures that only verify a portion of the data are not always shared or available, whereas root hashes are.  For discussion see for example https://botbot.me/freenode/dat/2018-01-20/?msg=95975498 .

I believe this could basically be implemented by exposing `Feed.prototype._getRootsToVerify` .  I imagine the implementation could be the same as `Feed.prototype.verify` but it would not call `crypto.tree` nor `crypto.verify`, rather returning the roots as-is.

Note: last PR I had accepted required spending some time on IRC to draw attention to it, and including tests and documentation updates.

**Comment by denim2x** [comment]
@xloem [Here](https://github.com/denim2x/hypercore/commit/36ac97a3e6916a8c7ce0aad8ff368621d8ccc319#diff-168726dbe96b3ce427e7fedce31bb0bc) is an attempt at implementing access to root hashes; what is the expected behaviour of `verify` in this case?

**Comment by xloem** [comment]
@denim2x thank you so much for this work.

I was originally imagining a new api function, with ‘verify’ maintaining its existing behavior, but I personally think your solution of adding the behavior to ‘verify’ to be great.

Would you be able to add test coverage, submit a pull request, and work with mafintosh to have the change merged?

**Comment by denim2x** [comment]
@xloem I'll do my best 😃
