### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onmessage' of null

### ISSUE THREAD

**Issue by substack** [mafintosh/hypercore#15]
In the browser with https://github.com/substack/spellcast I'm getting:

```
Uncaught TypeError: Cannot read property 'onmessage' of null
```

from this spot in lib/protocol.js:

https://github.com/mafintosh/hypercore/blob/master/lib/protocol.js#L320:

```
  if (handle.onmessage) handle.onmessage(type, message)
```

**Comment by substack** [comment]
I get the original error when I do replication with `{ encrypted: false }`. When I turn encryption back on, I get: `Error: Channel is not open yet` from https://github.com/mafintosh/hypercore/blob/master/lib/protocol.js#L294

**Comment by mafintosh** [comment]
i think this is fixed now. if not re-open
