### ISSUE TITLE
What about refactoring ?

### ISSUE THREAD

**Issue by yuriy-yarosh** [mafintosh/hypercore#158]
I've been writting some typings for hypercore in openrealrecord/[#8](https://github.com/xloem/openrealrecord/issues/8), so had reviewed some portion of the hypercore / hyperdb / hyperdiscovery codebase. Well, it's not great... From the QA perspective there are some flaws, and overall API is inconsistent.

• @mafintosh what do you think about improving code coverage, adding some mutational testing support, newer ES6+ features (promises, async/await, etc) and some TypeScript via Babel7 ?

• Also I'd like to propose some cancelable streams with FRP on top of [most.js](https://github.com/cujojs/most) to reduce the amount of boilerplate code and increase maintability ?

• What do you think about using google's [protobuf impl](https://www.npmjs.com/package/google-protobuf) instead of [protocol-buffers](https://www.npmjs.com/package/protocol-buffers) ?

And... from the performance perspective, JavaScript stuff haven't been designed to deliver the best possible performance, but it's possible to deliver good development experience and smooth the rough edges via profiling / flamegraphs and some further Rust/C/C++/ASM FFI, it's especially handy nowadays with Node10.

**Comment by mafintosh** [comment]
Feel free to open individual small PRs to improve anything you want. We have had very few issues in the upstream deps with hypercore as it is, so no major changes, including API changes, are likely to happen here.

Also please be respectful of people's work when opening issues like this. Lot of people put a ton of work and time into to this.

**Comment by yuriy-yarosh** [comment]
> Lot of people put a ton of work and time into to this.

Well, there are flaws, and there's nothing personal or disrespectful in pointing 'em out.
It's just people make it personal due to individual compensational psychological needs, [Ikea effect](https://en.wikipedia.org/wiki/IKEA_effect) etc.

**Comment by pfrazee** [comment]
@yuriy-yarosh 🖕

**Comment by yuriy-yarosh** [comment]
@pfrazee nice one, don't be a jerk, and I hope you've got something to reply [over here](https://github.com/mafintosh/hypercore/issues/155#issuecomment-392353087).
