### ISSUE TITLE
Implement util.inspect.custom

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/hypercore#161]
We should implement the util.inspect.custom symbol to make the hypercores print nicer to stdout

**Comment by yoshuawuyts** [comment]
What kind of output did you have in mind?

We can reach parity in Rust with this through the `Display` trait, so I'm kind of curious.

**Comment by mafintosh** [comment]
@yoshuawuyts 

Something like?

`Hypercore(key={first 6 hex}..., length={n}, byteLength={n}, peers={amount-of-peers})`

If there any important debugging information I'm missing?

**Comment by pfrazee** [comment]
I'm +1. Might include the dkey.

**Comment by mafintosh** [comment]
Fixed in master
