### ISSUE TITLE
Signatures not getting sent with data by Beaker

### ISSUE THREAD

**Issue by pfrazee** [mafintosh/hypercore#183]
Beaker isn't sending a signature with its proofs. I'm still isolating why. Here's what I've got so far:

 - `Feed.prototype.proof()` is calculating `needsSig` to be `false`. This causes Hypercore to avoid fetching the signature.
 - `needsSig` is `false` because `TreeIndex.prototype.proof()` is returning `verifiedBy: 0`
 - `TreeIndex.prototype.proof()` is returning `verifiedBy: 0` because it reaches https://github.com/mafintosh/hypercore/blob/master/lib/tree-index.js#L67

I don't totally understand the logic of https://github.com/mafintosh/hypercore/blob/master/lib/tree-index.js#L53-L65 so I can't trace the cause further. I ran `audit()` on the metadata and content hypercores and got no invalid blocks.

There's a pretty good indication that this is affecting multiple people. Fritter went quiet!

LMK what else you need.

**Comment by mafintosh** [comment]
Should be fixed now
