### ISSUE TITLE
Should calling `feed.open` ensure that `feed.blocks` is populated?

### ISSUE THREAD

**Issue by paulkernfeld** [mafintosh/hypercore#19]
The documentation for `feed.open` suggests that `feed.blocks` will be populated when the callback happens, but this doesn't seem to be case. So I guess either (a) this is a bug or (b) the docs should explain both what `open` does and how to get `feed.blocks` property to be populated.

BTW, I love the new feeds! 😊

The result of this code is `AssertionError: undefined == 1`
```
var assert = require('assert')
var memdb = require('memdb')
var hypercore = require('hypercore')

var db = memdb()
var core = hypercore(db)
var feed1 = core.createFeed()
feed1.append('meow')

var core2 = hypercore(db)
var feed2 = core2.createFeed(feed1.key)
feed2.open(function (err) {
  assert.equal(feed2.blocks.length, 1)
})
```

**Comment by paulkernfeld** [comment]
Okay, this is dumb, `feed.blocks` is an integer! Sorry about that!

**Comment by mafintosh** [comment]
Ah yes. The docs could be more clear about that though
