### ISSUE TITLE
Read stream 'end' isn't emitted when the stream has no 'data' listener

### ISSUE THREAD

**Issue by lachenmayer** [mafintosh/hypercore#203]
Heya, I've noticed that when I don't have a 'data' listener on the stream created by `createReadStream`, my 'end' listener is never called, as below:

```js
const hypercore = require('hypercore')
const feed = hypercore('data')

feed
  .createReadStream()
  .on('end', () => console.log("i expect this to log but it doesn't"))

feed
  .createReadStream()
  .on('data', console.log)
  .on('end', () => console.log('this logs just fine'))
```

This also happens when something has already been appended to the feed, so it's not the same issue as #43. (the new related issues feature is awesome 😎)

(I don't have a data listener because I am piping it to a through stream with some effects, and I don't care about the actual return value)

Cheers :)

**Comment by mafintosh** [comment]
That’s how Node.js streams work. The “data” listener is kinda magic as it puts the stream into “flowing mode” when makes it emit end when there is no more data to be read. You can put the stream into flowing mode by piping it somewhere or calling .resume() on it as well

**Comment by lachenmayer** [comment]
Ah, Node.js stream semantics bite me yet again... The strange thing is that I _am_ piping it somewhere - in my code it looks something like this:

```js
const hypercore = require('hypercore')
const feed = hypercore(require('random-access-memory'))
const through = require('through2')

feed
  .createReadStream()
  .pipe(
    through((chunk, enc, cb) => {
      console.log(chunk)
      cb(null, null)
    })
  )
  .on('end', () => console.log("i expect this to log but it doesn't"))

feed
  .createReadStream()
  .on('data', console.log)
  .on('end', () => console.log('this logs just fine'))
```

Still does not log!

**Comment by mafintosh** [comment]
@lachenmayer move the on(‘end’) before your pipe as pipe returns your through stream. You also need to put the through stream in flowing mode :)

**Comment by lachenmayer** [comment]
All good - am just using `resume()` now, thank you!
