### ISSUE TITLE
Option to update the merkle tree as soon as someone hints a new proof

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/hypercore#204]
Right now the merkle tree data is only updated when an index >= feed.length is downloaded.

This is great for most use-cases, as fetching new merkle proofs can be computationally expensive as it requires asymmetric crypto, but when running in sparse mode using an external sparse friendly data structure such as a trie, we need a way to tell hypercore to try and fetch a merkle update as soon as another peer sends a HAVE message that they have something >= feed.length.

You can currently implement this yourself using the update api like so:

``` js
feed.update(function loop () {
  console.log('new merkle proof was fetches, ie feed.length changed')
  feed.update(loop)
})
```

I think we should add an option to Hypercore that makes it run that code internally to more officially support this use case.

I suggest we call this flag "verifyRemoteLength" as that is basically what the above snippet does from
a users point of view.

As soon a another peer hint that they have a longer feed that us, (is feed.remoteLength > feed.length) then Hypercore will try to verify that, that is indeed the case by fetching a merkle proof from the peer and updating it's local length if verified.

**Comment by pfrazee** [comment]
👍 to the feature, let me bikeshed the flag name. First, does this cause the metadata feed to automatically download, or does it just fetch the *proof*?

**Comment by mafintosh** [comment]
@pfrazee only the proof

**Comment by pfrazee** [comment]
Right okay. I might just suggest calling it `autoVerifyRemoteLength`, but otherwise I'm +1.
