### ISSUE TITLE
Bug `opts.expectedFeeds` ignored when stream present

### ISSUE THREAD

**Issue by telamon** [mafintosh/hypercore#219]
In [`lib/replicate.js:15`](https://github.com/mafintosh/hypercore/blob/master/lib/replicate.js#L15) we have the following code:
```js
 if (!stream) {
    if (!opts.expectedFeeds) opts.expectedFeeds = 1
    if (!opts.id) opts.id = feed.id
    stream = protocol(opts)
  }
```
If a stream is not provided, then `expectedFeeds` is optionally lazy-initialized and the opts are passed onto `hypercore-protocol`

I'm attempting to replicate a hyperdrive by passing a stream:

```js
drive.replicate({ stream: myStream })
```
Hyperdrive properly reports that it's a composite-core consisting of [2 feeds](https://github.com/mafintosh/hyperdrive/blob/v10.0.0-rc2/index.js#L674).

But when `opts.stream` was passed, then `opts.expectedFeeds` is completely ignored which causes hyperdrive to prematurely finish replication before the `content` core has been replicated.

I believe this is a bug and that a second condition should be added:
```js
 if (!stream) {
    if (!opts.expectedFeeds) opts.expectedFeeds = 1
    if (!opts.id) opts.id = feed.id
    stream = protocol(opts)
  } else if (opts.expectedFeeds) {   // Fix
    stream.expectedFeeds += opts.expectedFeeds
  }
```
Can someone verify?

**Comment by mafintosh** [comment]
Sounds like a likely bug. In any case adding a test for that would be good :)

**Comment by telamon** [comment]
Wups, i didn't add a test for it, rather checked that previous tests didn't fail. which they did if you modify the initalization to more logically look like this:

```js
 if (!opts.expectedFeeds) opts.expectedFeeds = 1 // unconditional lazy init
 if (!stream) {
    if (!opts.id) opts.id = feed.id
    stream = protocol(opts)
  } else {
    stream.expectedFeeds += opts.expectedFeeds
  }
```

**Comment by telamon** [comment]
OK so I've added the test now, but I've hit a snag, all tests pass on my environment but Travis reports that all test-runs fail across all environments... I can't replicate the bug locally.

To be honest I'm a little bit overwhelmed by this issue. Keeping track of when a replication stream has finished replicating all feeds using the `expectedFeeds` counter is not very safe.

For instance it requires all hypercore dependents that provide a `replicate()` method to properly increment `stream.expectedFeeds` by the amount of feed's that they intend join into the protocol stream.

In hyperdrive's case, it dosen't even increment it, just set's the value plainly to `2` - which introduces a racing condition if you're using the same protocol-stream to replicate a core that properly __increments__ `expectedFeeds`.

There's also no standard way to query a hypercore-based model/composite-core for the amount of feed's it contains, so you can't workaround this issue on application level either.

So what I'm trying to say is that "fixing" this bug might just as well introduce more issues downstream... ( this issue does not affect 'live' streams ) 

Maybe a better idea is to redesign the current "Last feed ends the stream" logic in `hypercore-protocol`.

thoughts?

**Comment by mafintosh** [comment]
Very open to reimplementing it. We prob just need a way to tell the stream once it wants to end (when all current channels are closed) to wait incase we are adding a new channel asynchronously.

**Comment by telamon** [comment]
Yeah I understand the challenge, how about extending protocol with two new calls?

```js
const stream = coreA.replicate()

stream.hold() //  stream.nholds++
setTimeout(() => {
  coreB.replicate({ stream }) // might invoke release/hold internally.
  coreC.replicate({ stream })
  stream.release() // stream.nrelease++
}, 1000)

stream.hold() //  stream.nholds++
setTimeout(() => {
  coreD.replicate({ stream })
  stream.release() // stream.nrelease++
}, 500)

stream.onFeedFinishedHandler = () => {
  if (!stream.feeds.length && stream.nrelease >= stream.hold) stream.end()
}
```

It should be backwards compatible with the downstream i hope.. but it feels like hitting the problem with a bigger rock when the smaller rock didn't produce sufficient results. hehehe

**Comment by mafintosh** [comment]
@telamon can be closed?

**Comment by telamon** [comment]
Yes! nano-guard fixed it :)
