### ISSUE TITLE
light hyperdrive?

### ISSUE THREAD

**Issue by Unitech** [mafintosh/hypercore#23]
```bash
shant@onyx: ~/gridcontrol/gridcontrol
>>> tree node_modules | wc -l
17799

shant@onyx: ~/gridcontrol/gridcontrol
>>> tree node_modules/hyperdrive | wc -l
13394
```

node_modules de gridcontrol en entier = **17.799 fichiers**
module hyperdrive = **13.394 fichiers** soit ~70%

-- 

Temps installation gridcontrol 0.4.3:
- Intel(R) Atom(TM) CPU  C2750  @ 2.40GHz + 1GB network: **~1m30s** 
- Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz + wifi: **~22s** (cache?)
- Intel(R) Xeon(R) CPU E5-1410 v2 @ 2.80GHz + 1GB network: **~40s**

Note: need to install libtoolize for sodium compilation

**Comment by juliangruber** [comment]
@Unitech although I can read your comment it would have better chances written in english completely.

Hyperdrive with its dependencies is a lot of "files", yeah, but it's also solving a hard problem.

If you want to help hyperdrive / hypercore have shorter install times, it's probably most useful to go through it and each dependency to see if they include files that aren't used, or maybe include dependencies that aren't used.

**Comment by mafintosh** [comment]
@Unitech adding sodium prebuilds for latest node+linux now so you won't have to compile that in the future. otherwise what @juliangruber said is pretty spot on

**Comment by mafintosh** [comment]
sodium prebuilds added now

**Comment by Unitech** [comment]
Fuuuuuu ahaha, that was the wrong repository I wanted to comment on, feel so dumb right now ^^'

**Comment by mafintosh** [comment]
@Unitech nbd. the two projects are very related. i personally didn't even see that it was the wrong one.

**Comment by Unitech** [comment]
But yes I was digging deeper to maybe found a solution to this issue, it was not my attention to throw this kind of issue.

@mafintosh no I mean it's totally the wrong repository, as this issue was at first for a (currently) work-in-progress, private project

**Comment by mafintosh** [comment]
@Unitech ah. np. hope you solve your private issue then!

**Comment by Unitech** [comment]
If we find any way to make hypercore/hyperdrive lighter, for sure we will share the solution with you. If we can be of any help too do not hesitate to ask,

By the way hypercore/hyperdrive is just a pure awesomeness, thank you so much for this quality work guys.

**Comment by Unitech** [comment]
using https://github.com/JamieMason/shrinkpack reduced install time by 4x!
