### ISSUE TITLE
changelogs

### ISSUE THREAD

**Issue by noffle** [mafintosh/hypercore#235]
I think it could be very useful to downstream consumers if this module published changelog[1] entries. It'd be nice to get a high-level understanding of what is changing between minor and especially major versions.

 [1] https://keepachangelog.com/en/1.0.0/

**Comment by yoshuawuyts** [comment]
For a practical example; I've started doing this for async-std recently and people seem to be liking it a lot. https://github.com/async-rs/async-std/blob/master/CHANGELOG.md

Coupled with a tweet from our twitter account it drives a lot of traffic, and gives people a good sense of where we're heading. I find Dat stuff super interesting, but don't have the bandwidth to keep up daily. Having a changelog would help me a *lot* with staying up to date!

**Comment by aral** [comment]
It would definitely help me.

And keeping ne helps me when working on my own stuff too: e.g., https://source.ind.ie/site.js/app/blob/master/CHANGELOG.md

**Comment by mafintosh** [comment]
Yep good idea, will do for the next releases

**Comment by noffle** [comment]
hey, maybe let's reopen this? I think we still haven't started making changelogs.

**Comment by tinchoz49** [comment]
I few years ago we did this to maintain changelogs https://github.com/geut/chan/tree/master/packages/chan maybe can help.

**Comment by jwerle** [comment]
:pray:

**Comment by mafintosh** [comment]
Yep! pushing a v9 release tmw (hopefully!) with updated noise stuff. Will make sure to attach a changelog.

**Comment by ZoeDreams** [comment]
Thank you for your work :) Looking forward to testing it out.
