### ISSUE TITLE
registerExtension signature to send

### ISSUE THREAD

**Issue by substack** [mafintosh/hypercore#236]
Right now if you call `var ext = feed.registerExtension(name, handlers)`, in order to send messages inside your handlers, you need a reference to the `ext` object. This doesn't work very well for circumstances when you want to modularize your handlers:

``` js
feed.registerExtension(name, require('some-hypercore-extension-module'))
```

So I propose a new backwards-compatible api for extensions: if the `handlers` argument is a function, it will receive the extension object as its first argument. Then you can write fully self-contained extensions that can send as well as receive data:

``` js
feed.registerExtension(name, function (ext) {
  return {
    encoding: 'json',
    onmessage: function (msg, peer) {
      ext.send(msg.n+1)
    }
  }
})
```

**Comment by telamon** [comment]
I don't think there's many extensions out there yet so it dosen't have to be fully backwards compatible I suppose.
For now I've been using the following pattern to make my extensions self-contained:
```js
module.exports = function registrarAdapter(extensionHost) {
  const inst = new MyExt()
  // Inject transmitter
  inst._ext = extensionHost.registerExtension('MyExtension', inst)
  return inst
}

class MyExt {
  constructor () { ... }

  get encoding { ... }

  onerror (e) { ... }

  onmessage (msg, peer) {
    this._ext.send(peer, "some response")
  }

  start () { this._ext.broadcast('...') }
}
module.exports.MyExt = MyExt
```

Also while we're on the self-contained extension subject.
We might consider having an `onconnected(peer)` handler to signal the extension _when_ the proposed `send` method is ready to be used - but I am unsure of how much work that would take to implement.

**Comment by mafintosh** [comment]
Should be fixed in the above dependency commit :) Reinstall.
