### ISSUE TITLE
Extending hypercore?

### ISSUE THREAD

**Issue by paulkernfeld** [mafintosh/hypercore#4]
I'm interested in implementing a [BEP 44](http://www.bittorrent.org/beps/bep_0044.html)-like pubkey-to-value feature on top of hypercore (see mafintosh/hyperdrive#18). As I see it, this shouldn't be part of the hypercore library itself; it should live in a separate library that can be optionally hooked into a hypercore. I'm wondering if anyone has thoughts on how to do this, or if this is something that even should be done.

As far as principles for extending hypercore, here's what I'm thinking:
- Do not change or disrupt existing hypercore functionality; an extended hypercore should not send data that interferes with connected hypercores.
- Follow the [hypercore philosophy](https://github.com/mafintosh/hyperdrive/blob/master/SPECIFICATION.md).

Some specific situations:
- When creating new message types, choose high message ID numbers, leaving low message IDs for future hypercore functionality. 100 would be a good message ID. 10 would not.
- Do not reuse existing message types, since that could crash hypercores to which you connect.

**Comment by mafintosh** [comment]
This is a great idea. Would allow us to easily experiment with dynamic feeds as well (including your proposal).

I propose we expand the handshake to this

``` proto
message Handshake {
  required string protocol = 1;
  optional uint64 version = 2;
  required bytes id = 3;
  repeated string extensions = 4; // <-- new message
}
``` 

Then assuming alice and bob send a handshake to each other they would send an array of the extensions they support

```
// alice sends
{
  ...,
  extensions: ['my-new-extension', 'pauls-dynamic-feeds']
}

// bob sends
{
  ...,
  extensions: ['pauls-dynamic-feeds'] // does not support my-new-extension
}
```

The intersection of the two extensions will be the extensions both parties support. To pick the message tag numbers that the extension messages will be sent with we pick the array offsets of the extension messages and add 64 (64 is arbitrary - just so we in theory could support 64 officially spec'ed messages)

So given the above example, the intersection of alice and bob's extensions is `['pauls-dynamic-feeds']`

* alice will send messages for this extension with tag `64 + 1 = 65`
* bob will use tag `64 + 0 = 64`

This scheme makes it easier to create new extensions without having to reserve a tag number.

Makes sense?

**Comment by piedshag** [comment]
ok sweet. see you there

**Comment by piedshag** [comment]
I quite like the idea of adding extensions using a hypercore.use(extension) function (similar to feross' [bittorrent-protocol](https://github.com/feross/bittorrent-protocol#extension-api) library). And then you give the extension access to the feed api. I am happy to work on a pull request. What do you reckon?

**Comment by mafintosh** [comment]
@piedshag sounds good! i like the overall approach of @feross' .use api. open a pr and we can discuss it more in detail there.

**Comment by piedshag** [comment]
done [pr](https://github.com/mafintosh/hypercore/pull/5)

**Comment by mafintosh** [comment]
Extension API just landed, https://github.com/mafintosh/hypercore#extension-api

**Comment by mafintosh** [comment]
Out in 1.2.0

**Comment by mafintosh** [comment]
I should add the extension wire protocol to the spec though...
