### ISSUE TITLE
Add a timeout to feed.get (avoid memory leaks)

### ISSUE THREAD

**Issue by pfrazee** [mafintosh/hypercore#52]
If you call feed.get on a hypercore that you don't have locally, the function will enter a queue that waits until the requested block is added.

If the hypercore is not locally owned, there's no guarantee it will be found on the network. Therefore, it's important that the searching process aborts at some point.

This should happen in hypercore so that the callback can be released from memory.

**Comment by mafintosh** [comment]
👍 although it should be opt-in. `createFeed({timeout: 1000})` and `.get(index, {timeout: 1000}, cb)`

**Comment by pfrazee** [comment]
yeah agreed

**Comment by mafintosh** [comment]
.get has a timeout option now
