### ISSUE TITLE
checksum on data read

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/hypercore#55]
if external storage is used we should checksum data when reading

alternatively in the future we could consider adding a 'reject' message to the wire protocol so a remote peer could indicate that a message failed and then run the checksum

**Comment by maxogden** [comment]
reject-on-write seems better than hashing on read to me, since the writer is going to hash it anyway

**Comment by pfrazee** [comment]
If a read fails during replication, the current behavior is to destroy the connection with the failure. Is there another way to handle it for a failed verify-on-read? Perhaps by sending an unhave message?
