### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/hypercore#72]
Basically finish [sodium-javascript](https://github.com/mafintosh/sodium-javascript).

**Comment by guybrush** [comment]
maybe it could work with sodium compiled to wasm? https://github.com/jedisct1/libsodium/issues/475

**Comment by fasiha** [comment]
@mafintosh may have said in IRC that this was resolved via sodium-universal?

**Comment by mafintosh** [comment]
Indeed it is!
