### ISSUE TITLE
Allow me to roll back a hypercore to a previous version

### ISSUE THREAD

**Issue by watson** [mafintosh/hypercore#78]
For debugging purposes it would be really useful to be able to roll back a local hypercore to a previous version.

## My use-case

In [npm-dependency-db](https://github.com/watson/npm-dependency-db) we download blocks from a hypercore hosted by [npm-to-hypercore](https://github.com/wartson/npm-to-hypercore). At the moment the feed contains 2.7M blocks and if we want to debug something related to resuming downloads in very large feeds we sometimes have to re-download all blocks - this is very time- and bandwidth-consuming

It would therefore be nice if (on my local hypercore) I could roll back the data as if for instance the last 100,000 blocks was never downloaded.

**Comment by mafintosh** [comment]
See `feed.clear`
