### ISSUE TITLE
Strange `crypto_generichash` usage

### ISSUE THREAD

**Issue by indutny** [mafintosh/hypercore#93]
The arguments of `crypto_generichash` are:

- `output`
- `input` (almost unlimited size for our purposes)
- `key` (up to 64 byte long)

However, hypercore uses it as:

`crypto_generichash(out, Buffer.from('hypercore'), data)`

In our case `data` is a 32-byte public Elliptic Curve key.

Given that internally it uses BLAKE, the `key` and `input` are treated in very similar way, so this is cryptographically safe. However, it is very strange to see that it is used in reverse manner. Albeit, it is too late to fix discovery key, it may be a good idea to keep this in mind in the future unless this was intentional.

cc @mafintosh

**Comment by mafintosh** [comment]
As discussed on IRC this is intentional. We use like we used to use the hmac in earlier versions. As you mention either way should be secure. @emilbayes might have more input

**Comment by emilbayes** [comment]
`Buffer.from('hypercore')` is not the key here, so the parameters are not reversed. `data` however is a confusing choice for the variable name as that is actually the `key` and the buffer is the data. You have to know the key to find others and then the buffer is just an arbitrary constant. Right @mafintosh ?
