### ISSUE TITLE
Downloading metadata of a large archive sparsely: How to get progress and the possibility of calling readDir while metadata is still downloading.

### ISSUE THREAD

**Issue by e-e-e** [mafintosh/hypercore#98]
I have been experimenting with a *huge* Dat, 27921+ folders with a `metadata.data` file of about 950MB. Obviously even in sparse mode it takes a while to initially download the archive. 

I was just wondering: 

1) Is there a way of tracking the progress of this initial loading? I looked at how this is implemented in append-tree but could not find an obvious solution. I ended up tracking the download via watching the network traffic from the node process, but otherwise there was no indication.

2) Is there a way to access metadata that has been partially downloaded. I notice the append-tree list is waiting until all metadata is loaded before firing the callback on archive.readDir. It would be really useful to start being able to access the metadata for folders and files as a stream while they are being download.

3) Is there also a way to stream results from readDir, rather than all in one go. Even once we have the metadata back, readDir is quite a heavy operation returning a huge array in memory.

If these features don't exist but would be useful, I am happy to contribute a PR implementing solutions if you point me in the right architectural direction.

I really love the work you guys are doing. 
Thanks in advance for your help.

**Comment by mafintosh** [comment]
Hi! I have some initial questions, and will reply to the rest in more detail later :)

1. How is the dat structured? I.e. are all the folders in a one big root folder. If you are willing to share the dat with me that would be helpful as well.

2. Sparse loading of metadata should already work but right now you can create some dats that take longer to load depending on 1. We are working on making this even better in the future.

3. Not right now but that is coming (I have the same usecase personally). `readdir` returns an array because that is what node core does in fs but I'm gonna add an .createDirectoryStream() method soon.

You can set `{cached: true}` as an option to readdir/stat etc to *only* return the locally cached items btw. We might need some docs for that.

**Comment by e-e-e** [comment]
Thanks for such a quick reply.

1. Its structured like a calibre library. So yeah - a huge root folder of authors, and then each of those contain other folders. I just chatted with my collaborator and he said he had already shared the dat with you privately - it begins with 1d2c0c4089b4...

2. Yeah sparse loading works great - its just the initial loading of the metadata that is slow, for really understandable reasons - it takes a while to download 950+MB of data. But it would be great to expose some sort of progress on the construction of the initial append-tree. Our use case is that it would be nice to show gui progress. But also it would be helpful to be able to access readDir of the incomplete tree so we could begin processing the dat before its fully loaded. For some context - we are experimenting with a federated library system using dat as the base - https://github.com/e-e-e/dat-library and https://github.com/sdockray/dat-cardcat. Its very much a work in progress at the moment. 

3. Yeah its a real oversight in node I think - as other people have pointed out, readDir returning an array opens up vulnerability to DOS attacks. It’s been a live issue in node since january 2015 - https://github.com/nodejs/node/issues/583.

Thanks for the `{ cache: true }` trick.

**Comment by e-e-e** [comment]
Oh also - I just realised that I probably should have opened this issue on the hyperdrive repository not hypercore - apologies.

**Comment by e-e-e** [comment]
@mafintosh - just to let you know - I think I have discovered a nice why of getting progress on the initial download of metadata, and a list of the files as a stream by using the download event listener.

Here is an example of what I have working:
```js
const fs = require('fs');
const path = require('path');
const Dat = require('dat-node');
const protobuf = require('protocol-buffers');
const pretty = require('prettysize');

const messages = protobuf(fs.readFileSync(path.join(__dirname, 'schema.proto')))
const datkey = '7a9225a79f68f0a41d2d20c1827408eb25d5d8fecd4f49cfc8dfd97d0d0c004a'

Dat('./something', { key: datkey, sparse: true }, function (err, dat) {
  const stats = dat.trackStats();
  let progressCount = 0;
  dat.joinNetwork();

  dat.network.once('connection', function () {
    console.log('I connected to someone!')
    dat.archive.tree.feed.on('download', (i, d) => {
      progressCount++;
      if(i === 0) {
        const header = messages.Header.decode(d);
        console.log(header);
      } else {
        try {
          const block = messages.Node.decode(d);
          const progess = dat.archive.tree.feed.length ? (progressCount / dat.archive.tree.feed.length) * 100 : 0;
          console.log(`downloaded ${i}/${dat.archive.tree.feed.length}:`, block.name);

          console.log(`network: ${stats.peers.total || 0} peers (${pretty(stats.network.downloadSpeed)}) ${progess.toFixed(2)}% complete`)
          if (block.value) {
            const value = messages.Stat.decode(block.value);
            // console.log('values:', value);
          }
          if (block.paths) {
            // console.log('has paths');
          }
        } catch (e) {
          console.log('Something went wrong!');
        }
      }
    })
  })

  dat.archive.tree.feed.on('sync', (i, d) => {
    console.log('synced');
  })
})
```

Do you see anything wrong with hooking into the protocol at such a low level? Is this likely to break in horrific and unpredictable ways?

**Comment by e-e-e** [comment]
Oh also @mafintosh you can close this issue - as the changes in https://github.com/mafintosh/hypercore/pull/101 and your cache trick totally addesses all of my original concerns.

I still think it would be nice to have an iterator for readDir, but thats just sugar. Thanks for being so awesome.

**Comment by mafintosh** [comment]
Iterator is coming!! :)
